// test_dp1_inmem_init_equals_file.cpp -- Property test DP1: In-memory
// AMIO init equals file-based init.
//
// Feature: driver-io-regrid-perf
// Property 1: In-memory init equals file-based init.
//
// For any VALID AMIO manifest: writing that manifest to a temp file and
// calling amio_init(path, &core_b) must agree, outcome-for-outcome, with
// calling amio_init_from_string(content, "yaml", &core_a) on the same
// content.  Both must return AMIO_OK (the manifest is valid) and each
// must yield a non-null, usable core handle.  Both handles are finalized
// to avoid leaks.
//
// RapidCheck standalone (rc::check) wrapped in a Catch2 v3 TEST_CASE,
// matching the style in test_p21_snapshot_copy_correctness.cpp and
// test_p2_config_validity.cpp.  Min 100 iterations (RC_PARAMS
// max_success=100 via the ENVIRONMENT test property).
//
// **Validates: Requirements 2.1, 2.2**

#include <filesystem>
#include <fstream>
#include <string>

#include "generators.hpp"
#include "pbt_common.hpp"

// NOTE ON MPI: amio_init constructs the LOGS logger via
// configure_communicator(), which only calls MPI_Comm_rank when MPI has
// already been initialized.  This test does NOT initialize MPI (and does not
// link the MPI test listener), so the logger takes its MPI-uninitialized
// path -- exactly like the existing amio_init coverage in
// test_p2_config_validity.cpp (P2e).  This keeps the property focused on the
// init-equivalence contract without depending on a live MPI environment.

using namespace amio::detail;
using namespace amio::pbt;

// ===================================================================
// Reuse the P2 validity oracle: a Config generated by
// Arbitrary<Config> is only guaranteed to be within-range when it
// passes this predicate, so we gate on it (RC_PRE) to ensure the
// manifest we test is actually VALID.  This mirrors the valid-manifest
// approach in test_p2_config_validity.cpp (P2c/P2d/P2e).
// ===================================================================

static bool is_config_expected_valid(const Config &cfg) {
    if (cfg.staging_pool.buffer_count < 1 || cfg.staging_pool.buffer_count > 4096) {
        return false;
    }
    if (cfg.staging_pool.buffer_capacity_bytes < 1 || cfg.staging_pool.buffer_capacity_bytes > 1'073'741'824) {
        return false;
    }
    if (cfg.worker_pool.threads < 1 || cfg.worker_pool.threads > 256) {
        return false;
    }
    if (cfg.prefetch.depth < 1 || cfg.prefetch.depth > 1024) {
        return false;
    }
    if (cfg.prefetch.read_timeout_s < 1 || cfg.prefetch.read_timeout_s > 3600) {
        return false;
    }
    if (cfg.staging_timeout_ms < 1 || cfg.staging_timeout_ms > 60000) {
        return false;
    }
    if (cfg.backpressure.high_watermark > 0) {
        if (cfg.backpressure.low_watermark >= cfg.backpressure.high_watermark) {
            return false;
        }
        if (cfg.backpressure.high_watermark > cfg.backpressure.queue_capacity) {
            return false;
        }
    }
    static const std::vector<std::string> valid_codecs = {"blosc", "zstandard", "libaec", "lossless_jpeg2000"};
    for (const auto &codec : cfg.codec.lossless_allow_list) {
        if (std::find(valid_codecs.begin(), valid_codecs.end(), codec) == valid_codecs.end()) {
            return false;
        }
    }
    if (!cfg.codec.active_codec.empty()) {
        if (std::find(valid_codecs.begin(), valid_codecs.end(), cfg.codec.active_codec) == valid_codecs.end()) {
            return false;
        }
        if (!cfg.codec.lossless_allow_list.empty()) {
            if (std::find(cfg.codec.lossless_allow_list.begin(), cfg.codec.lossless_allow_list.end(), cfg.codec.active_codec) ==
                cfg.codec.lossless_allow_list.end()) {
                return false;
            }
        }
    }
    return true;
}

// ===================================================================
// Property Test DP1: In-memory init equals file-based init.
//
// For any valid manifest content: amio_init_from_string(content) and
// amio_init(path) both return AMIO_OK and each mints a usable (non-null)
// core handle.  Both handles are finalized.
//
// **Validates: Requirements 2.1, 2.2**
// ===================================================================

TEST_CASE("Feature: driver-io-regrid-perf, Property 1: in-memory init equals file-based init", "[pbt][driver-io-regrid-perf][dp1][inmem_init]") {
    auto result = rc::check(
        "amio_init_from_string(content) agrees with amio_init(path) for a valid "
        "manifest: both succeed and yield a usable core handle",
        []() {
            // Generate a VALID manifest Config (same style as P2c/P2d/P2e).
            auto cfg = *rc::gen::arbitrary<Config>();
            RC_PRE(is_config_expected_valid(cfg));

            // Produce the YAML content once; both paths use the same bytes.
            std::string yaml = ConfigLoader::serialize(cfg);

            // Write the same content to a temp file for the file-based path.
            TempDir tmp;
            std::string manifest_path = write_manifest(tmp, yaml, "manifest.yaml");

            // In-memory init.
            amio_core_handle core_a = nullptr;
            amio_status_t rc_a = amio_init_from_string(yaml.c_str(), "yaml", &core_a);

            // File-based init.
            amio_core_handle core_b = nullptr;
            amio_status_t rc_b = amio_init(manifest_path.c_str(), &core_b);

            // The two entry points must agree on the outcome.  Compare as
            // plain ints so RapidCheck does not try to pretty-print the
            // (opaque) handle types on failure.
            bool status_agrees = (rc_a == rc_b);
            RC_ASSERT(status_agrees);

            // The manifest is valid, so both must succeed with a usable handle.
            bool a_ok = (rc_a == AMIO_OK);
            bool b_ok = (rc_b == AMIO_OK);
            RC_ASSERT(a_ok);
            RC_ASSERT(b_ok);

            // Each path must mint a non-null, usable core handle.  Reduce to a
            // bool before RC_ASSERT: amio_core_handle is a void* and this
            // RapidCheck build cannot render a void* in a failure message.
            bool a_handle_valid = (core_a != nullptr);
            bool b_handle_valid = (core_b != nullptr);
            RC_ASSERT(a_handle_valid);
            RC_ASSERT(b_handle_valid);

            // Finalize both handles to avoid leaks.
            if (core_a != nullptr) {
                amio_finalize(core_a);
            }
            if (core_b != nullptr) {
                amio_finalize(core_b);
            }
        });

    REQUIRE(result);
}
