// test_p3_config_roundtrip.cpp -- Property test P3: Configuration round-trip.
//
// Property 3: For any Config produced by parse: serialize then re-parse
// yields deeply equal Config (field set, values, nesting).
//
// Steps:
//   1. Generate a valid Config via Arbitrary<amio::detail::Config>
//   2. Call ConfigLoader::serialize(config) to produce a YAML string
//   3. Write the YAML string to a temp file
//   4. Call ConfigLoader::parse(path, out_config, err) to re-parse
//   5. Assert parse succeeds (returns AMIO_OK)
//   6. Assert the re-parsed Config is deeply equal to the original
//
// Min 100 iterations.
//
// CRITICAL: Uses REAL ConfigLoader (src/config/config_loader.hpp).
//           NO mock backends.
//
// **Validates: Requirements R11.5**

#include "pbt_common.hpp"
#include "generators.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>

// ===================================================================
// Test Case: Configuration round-trip property.
//
// For any valid Config generated by Arbitrary<Config>:
//   serialize → write to file → parse → deeply equal to original.
// ===================================================================

TEST_CASE("P3: Configuration round-trip - serialize then re-parse yields equal Config",
          "[pbt][p3][config][roundtrip]") {
    auto result = rc::check(
        "For any valid Config: serialize → parse yields deeply equal Config",
        [](amio::detail::Config original) {
            // Step 2: Serialize the config to YAML.
            std::string yaml = amio::detail::ConfigLoader::serialize(original);
            RC_ASSERT(!yaml.empty());

            // Step 3: Write the YAML string to a temp file.
            amio::pbt::TempDir tmp;
            std::string manifest_path = tmp.file("roundtrip.yaml");
            {
                std::ofstream ofs(manifest_path);
                RC_ASSERT(ofs.is_open());
                ofs << yaml;
                ofs.close();
            }
            RC_ASSERT(std::filesystem::exists(manifest_path));

            // Step 4: Re-parse the file via ConfigLoader::parse.
            amio::detail::Config reparsed;
            amio::detail::ValidationError verr;
            amio_err_t parse_rc = amio::detail::ConfigLoader::parse(
                manifest_path, reparsed, verr);

            // Step 5: Assert parse succeeds.
            RC_ASSERT(parse_rc == AMIO_OK);

            // Step 6: Assert deep equality on all fields.

            // staging_pool fields
            RC_ASSERT(reparsed.staging_pool.buffer_count ==
                      original.staging_pool.buffer_count);
            RC_ASSERT(reparsed.staging_pool.buffer_capacity_bytes ==
                      original.staging_pool.buffer_capacity_bytes);

            // worker_pool fields
            RC_ASSERT(reparsed.worker_pool.threads ==
                      original.worker_pool.threads);

            // prefetch fields
            RC_ASSERT(reparsed.prefetch.depth ==
                      original.prefetch.depth);
            RC_ASSERT(reparsed.prefetch.read_timeout_s ==
                      original.prefetch.read_timeout_s);

            // staging_timeout_ms
            RC_ASSERT(reparsed.staging_timeout_ms ==
                      original.staging_timeout_ms);

            // backend
            RC_ASSERT(reparsed.backend == original.backend);

            // codec fields
            RC_ASSERT(reparsed.codec.active_codec ==
                      original.codec.active_codec);
            RC_ASSERT(reparsed.codec.lossless_allow_list.size() ==
                      original.codec.lossless_allow_list.size());
            // Verify same elements (order preserved by serialize)
            for (std::size_t i = 0; i < original.codec.lossless_allow_list.size(); ++i) {
                RC_ASSERT(reparsed.codec.lossless_allow_list[i] ==
                          original.codec.lossless_allow_list[i]);
            }

            // backpressure fields
            RC_ASSERT(reparsed.backpressure.low_watermark ==
                      original.backpressure.low_watermark);
            RC_ASSERT(reparsed.backpressure.high_watermark ==
                      original.backpressure.high_watermark);
            RC_ASSERT(reparsed.backpressure.queue_capacity ==
                      original.backpressure.queue_capacity);

            // worker_pool optional fields
            RC_ASSERT(reparsed.worker_pool.cpu_cores ==
                      original.worker_pool.cpu_cores);
            RC_ASSERT(reparsed.worker_pool.numa_domain ==
                      original.worker_pool.numa_domain);

            // io_ranks
            RC_ASSERT(reparsed.io_ranks == original.io_ranks);

            // Final comprehensive equality check using operator==
            RC_ASSERT(reparsed == original);
        });
    REQUIRE(result);
}

// ===================================================================
// Test Case: Configuration round-trip via parse_string (no file I/O).
//
// Same property but exercises the parse_string path directly,
// eliminating file system as a variable.
// ===================================================================

TEST_CASE("P3: Configuration round-trip via parse_string",
          "[pbt][p3][config][roundtrip][string]") {
    auto result = rc::check(
        "For any valid Config: serialize → parse_string yields deeply equal Config",
        [](amio::detail::Config original) {
            // Serialize the config to YAML.
            std::string yaml = amio::detail::ConfigLoader::serialize(original);
            RC_ASSERT(!yaml.empty());

            // Re-parse from string.
            amio::detail::Config reparsed;
            amio::detail::ValidationError verr;
            amio_err_t parse_rc = amio::detail::ConfigLoader::parse_string(
                yaml, "yaml", reparsed, verr);

            // Assert parse succeeds.
            RC_ASSERT(parse_rc == AMIO_OK);

            // Assert deep equality.
            RC_ASSERT(reparsed == original);
        });
    REQUIRE(result);
}
