####################################################################
# check_c99_isolation.cmake
#
# Run as a `cmake -P` script from the CTest target
# `amio_header_c99_isolation`.  Verifies R10.1, R10.2, R13.6 by
# compiling include/amio/amio.h with:
#
#     ${AMIO_C_COMPILER} -std=c99 -pedantic -Werror -Wall -Wextra \
#                        -I${AMIO_INCLUDE_DIR}                    \
#                        -c -o /dev/null amio.h
#
# Any non-C99 token, any header outside {<stdint.h>, <stddef.h>,
# <stdbool.h>}, or any transitive include of an eckit/TensorStore/
# netCDF/g2c header path will cause the compile to fail.
#
# Required CMake variables (set by the parent test):
#   AMIO_C_COMPILER      absolute path to the C compiler
#   AMIO_PUBLIC_HEADER   absolute path to include/amio/amio.h
#   AMIO_INCLUDE_DIR     absolute path to include/  (so #include
#                        "amio/amio.h" inside an in-tree probe TU
#                        resolves)
#   AMIO_WORK_DIR        scratch directory; created if missing
####################################################################

foreach(_var IN ITEMS AMIO_C_COMPILER AMIO_PUBLIC_HEADER AMIO_INCLUDE_DIR AMIO_WORK_DIR)
    if(NOT DEFINED ${_var} OR "${${_var}}" STREQUAL "")
        message(FATAL_ERROR "check_c99_isolation: required variable ${_var} not set")
    endif()
endforeach()

if(NOT EXISTS "${AMIO_C_COMPILER}")
    message(FATAL_ERROR
        "check_c99_isolation: C compiler not found at '${AMIO_C_COMPILER}'")
endif()
if(NOT EXISTS "${AMIO_PUBLIC_HEADER}")
    message(FATAL_ERROR
        "check_c99_isolation: amio.h not found at '${AMIO_PUBLIC_HEADER}'")
endif()

file(MAKE_DIRECTORY "${AMIO_WORK_DIR}")

# Compile a probe translation unit that includes amio.h via the
# project include path.  Using a real .c file (rather than -x c
# against amio.h itself) ensures GCC picks up the C99 dialect and
# emits a normal object that we can throw away.
set(_probe "${AMIO_WORK_DIR}/probe_c99.c")
file(WRITE "${_probe}"
"/* Auto-generated by check_c99_isolation.cmake.\n"
" * Compiles amio.h under -std=c99 -pedantic -Werror to enforce the\n"
" * C99-only contract on the AMIO public surface (R10.1, R10.2, R13.6).\n"
" */\n"
"#include \"amio/amio.h\"\n"
"\n"
"int amio_c99_isolation_probe(void) { return 0; }\n")

execute_process(
    COMMAND ${AMIO_C_COMPILER}
            -std=c99 -pedantic -Werror -Wall -Wextra
            -I${AMIO_INCLUDE_DIR}
            -c ${_probe}
            -o ${AMIO_WORK_DIR}/probe_c99.o
    WORKING_DIRECTORY ${AMIO_WORK_DIR}
    RESULT_VARIABLE   _rc
    OUTPUT_VARIABLE   _out
    ERROR_VARIABLE    _err
)

if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
        "amio_header_c99_isolation FAILED.\n"
        "  Compiler : ${AMIO_C_COMPILER}\n"
        "  Header   : ${AMIO_PUBLIC_HEADER}\n"
        "  Exit     : ${_rc}\n"
        "  stdout   :\n${_out}\n"
        "  stderr   :\n${_err}\n"
        "\n"
        "The AMIO public umbrella header MUST compile cleanly under\n"
        "`gcc -std=c99 -pedantic -Werror -c amio.h` with no third-\n"
        "party include paths (R10.1, R10.2, R13.6).  Inspect the\n"
        "diagnostics above and remove any non-C99 token or any\n"
        "transitive include of an eckit / TensorStore / netCDF /\n"
        "HDF5 / nceplibs-g2c header from the public surface.")
endif()

message(STATUS "amio_header_c99_isolation: PASSED")
