# ####################################################################################################################################################
# check_cxx_inclusion.cmake
#
# Run as a `cmake -P` script from the CTest target `amio_header_cxx_inclusion`.  Verifies R10.3 by compiling include/amio/amio.h as C++20:
#
# ${AMIO_CXX_COMPILER} -std=c++20 -Wall -Wextra \ -I${AMIO_INCLUDE_DIR}    \ -c -o /dev/null amio.h
#
# The compile must succeed because every public declaration in amio.h is wrapped in `#ifdef __cplusplus extern "C" { ... }` guards (R10.3).  The probe
# TU also references the umbrella typedef from a `extern "C"` callback to confirm the linkage attribute is observable to the C++ compiler.
#
# Required CMake variables (set by the parent test): AMIO_CXX_COMPILER    absolute path to the C++ compiler AMIO_PUBLIC_HEADER   absolute path to
# include/amio/amio.h AMIO_INCLUDE_DIR     absolute path to include/ AMIO_WORK_DIR        scratch directory; created if missing
# ####################################################################################################################################################

foreach(_var IN ITEMS AMIO_CXX_COMPILER AMIO_PUBLIC_HEADER AMIO_INCLUDE_DIR AMIO_WORK_DIR)
    if(NOT DEFINED ${_var} OR "${${_var}}" STREQUAL "")
        message(FATAL_ERROR "check_cxx_inclusion: required variable ${_var} not set")
    endif()
endforeach()

if(NOT EXISTS "${AMIO_CXX_COMPILER}")
    message(FATAL_ERROR "check_cxx_inclusion: C++ compiler not found at '${AMIO_CXX_COMPILER}'")
endif()
if(NOT EXISTS "${AMIO_PUBLIC_HEADER}")
    message(FATAL_ERROR "check_cxx_inclusion: amio.h not found at '${AMIO_PUBLIC_HEADER}'")
endif()

file(MAKE_DIRECTORY "${AMIO_WORK_DIR}")

# The probe references the public typedef behind an `extern "C"` function pointer.  This forces the C++ front-end to honour the linkage decoration and
# would fail to compile if the `extern "C"` guard around amio.h's declarations were missing or malformed.
set(_probe "${AMIO_WORK_DIR}/probe_cxx.cpp")
file(
    WRITE "${_probe}"
    "// Auto-generated by check_cxx_inclusion.cmake.\n"
    "// Verifies the AMIO public header parses cleanly under C++20\n"
    "// thanks to the extern \"C\" guard (R10.3).\n"
    "#include \"amio/amio.h\"\n"
    "\n"
    "// Take the address of an extern \"C\" function pointer typed against\n"
    "// the public opaque-handle alias.  This compiles only when amio.h\n"
    "// declares amio_core_handle inside an extern \"C\" block (or in\n"
    "// global C-compatible scope) and does not pull any C++ symbol into\n"
    "// the public namespace.\n"
    "extern \"C\" {\n"
    "    typedef int (*amio_probe_init_fn)(amio_core_handle*);\n"
    "}\n"
    "\n"
    "static int amio_cxx_inclusion_probe(amio_probe_init_fn fn,\n"
    "                                    amio_core_handle*  out) {\n"
    "    return fn ? fn(out) : 0;\n"
    "}\n"
    "\n"
    "int main(void) {\n"
    "    amio_core_handle h = 0;\n"
    "    return amio_cxx_inclusion_probe(0, &h);\n"
    "}\n")

execute_process(
    COMMAND ${AMIO_CXX_COMPILER} -std=c++20 -Wall -Wextra -I${AMIO_INCLUDE_DIR} -c ${_probe} -o ${AMIO_WORK_DIR}/probe_cxx.o
    WORKING_DIRECTORY ${AMIO_WORK_DIR}
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err)

if(NOT _rc EQUAL 0)
    message(
        FATAL_ERROR
            "amio_header_cxx_inclusion FAILED.\n"
            "  Compiler : ${AMIO_CXX_COMPILER}\n"
            "  Header   : ${AMIO_PUBLIC_HEADER}\n"
            "  Exit     : ${_rc}\n"
            "  stdout   :\n${_out}\n"
            "  stderr   :\n${_err}\n"
            "\n"
            "The AMIO public umbrella header MUST compile cleanly under\n"
            "`g++ -std=c++20 -c amio.h` (R10.3).  Verify that every\n"
            "declaration is wrapped in:\n"
            "    #ifdef __cplusplus\n"
            "    extern \"C\" {\n"
            "    #endif\n"
            "    ...\n"
            "    #ifdef __cplusplus\n"
            "    }\n"
            "    #endif")
endif()

message(STATUS "amio_header_cxx_inclusion: PASSED")
